# Generated by Django 5.0.2 on 2025-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ky', models.CharField(max_length=500)),
                ('title_ru', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('annotation_ky', models.TextField()),
                ('annotation_ru', models.TextField()),
                ('annotation_en', models.TextField()),
                ('keywords_ky', models.TextField()),
                ('keywords_ru', models.TextField()),
                ('keywords_en', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
